export const ACTIVE_TRANSACTION = 'ACTIVE_TRANSACTION';
export const ACTIVE_PRESENTATION_DEFINITION = 'ACTIVE_PRESENTATION_DEFINITION';
export const SCHEME = 'scheme';
export const DEFAULT_SCHEME = 'eudi-openid4vp://';
